### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by shriram10567**
I have added test cases and removed redundant functionality in views_nested_details

### CODE REVIEW

**Comment by Natkeeran** [comment]
@shriram1056 

Tested this.  Indeed, we don't seem to be using the title and description config options.  hook_help is a standard fn, would leave that one in.  If you put that in, I'll merge this.  sorry for taking long to review, and thank you for this.

**Comment by shriram10567** [comment]
@Natkeeran 

Thanks for taking the time to look at my pull request. I have added hook_help just like you said.

**Comment by Natkeeran** [comment]
@shriram1056 

You need to implement the views_nested_details_help hook, not the islandora_help hook.

**Comment by Natkeeran** [comment]
@shriram1056 

https://github.com/Natkeeran/views_nested_details/pull/3/files

you can copy the original help method.  That should do it.  Thanks.

**Pull request merged**
